// tabs-stencil/src/components/dk-tabs/dk-tabs.tsx
import { Component, Element, Prop, State } from "@stencil/core";

@Component({
  tag: "dk-tabs",
  styleUrl: "dk-tabs.css",
  shadow: true
})
export class Tabs {
  /**
   * Index of the selected tab.
   */
  @Prop({
    mutable: true,
    reflectToAttr: true
  })
  selected = 0;

  @Element()
  el: HTMLElement;

  @State()
  tabs: HTMLDkTabElement[] = [];

  componentDidLoad() {
    this.updateTabs(this.el.shadowRoot.querySelector("slot"));
  }

  updateTabs(slot) {
    if (slot) {
      this.tabs = slot.assignedNodes({ flatten: true }).filter(el => {
        return el.nodeName === "DK-TAB";
      });
    } else {
      // this is for Browser not supporting HTMLSlotElement#assignedNodes
      this.tabs = Array.from(this.el.querySelector("#panels").children) as HTMLDkTabElement[];
    }
    this.selectTab(this.selected);
  }

  selectTab(idx: number) {
    this.selected = idx;
    for (let i = 0, tab; (tab = this.tabs[i]); ++i) {
      const selected = i === idx;
      tab.setAttribute("aria-hidden", !selected);
      // set style.display for Edge (CSS not working)
      if (selected) {
        tab.style.display = "";
      } else {
        tab.style.display = "none";
      }
    }
  }

  render() {
    return (
      <div>
        <div id="tabs">
          {this.tabs.map((tab: HTMLDkTabElement, index: number) => (
            <div title={tab.title} onClick={() => this.selectTab(index)}>
              {tab.title}
            </div>
          ))}
        </div>
        <div id="panels">
          <slot></slot>
        </div>
      </div>
    );
  }
}

// tabs-angular/src/app/dk-tabs/dk-tabs.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { DkTabComponent } from '../dk-tab/dk-tab.component';

@Component({
  selector: 'dk-tabs',
  templateUrl: './dk-tabs.component.html',
  styleUrls: ['./dk-tabs.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class DkTabsComponent {

  tabs: DkTabComponent[];

  @Input() selected: number;

  slotChange($event) {
    this.tabs = $event.target.assignedNodes({ flatten: true }).filter(el => {
      return el.nodeName === "DK-TAB";
    });
    this.selectTab(this.selected || 0);
  }

  selectTab(idx: number) {
    this.selected = idx;
    for (let i = 0, tab; (tab = this.tabs[i]); ++i) {
      const selected = i === idx;
      tab.setAttribute("aria-hidden", !selected);
      // set style.display for Edge (CSS not working)
      if (selected) {
        tab.style.display = "";
      } else {
        tab.style.display = "none";
      }
    }
  }

}

<div>
  <div id="tabs">
      <div *ngFor="let tab of tabs; index as idx" [title]="tab.title" (click)="selectTab(idx)">
        {{tab.title}}
      </div>
  </div>
  <div id="panels">
    <slot (slotchange)="slotChange($event)"></slot>
  </div>
</div>
